apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base

# El bump de versión se hace aquí: cambia newTag y ArgoCD sincroniza el deploy.
images:
  - name: ghcr.io/joakim31/lab04-registry
    newName: ghcr.io/joakim31/lab04-registry
    newTag: "17216404006c69e20dfeb18ff2179d23d904ca1a"

replicas:
  - name: app
    count: 3
